import React, { useContext, useState } from "react";
import styles from "./MainContainer.module.scss";

import Head from "next/head";
import { Header, Carousel, Info, LightBox } from "components";

import BasketContext from "../../contexts/BasketContext";

export const MainContainer: React.FunctionComponent = () => {
    //
    const context = useContext(BasketContext);
    const [open, setOpen] = context.open;
    const [zoom, setZoom] = useState<boolean>(false);
    //
    return (
        <div
            className={` ${styles.main_container}  ${
                zoom ? styles.main_container_background_zoom : null
            } ${open ? styles.main_container_background_mobile : null} `}
        >
            <Head>
                <title>Frontend Mentor | E-commerce product page</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/images/favicon-32x32.png" />
            </Head>

            <Header />

            <main className={styles.main}>
                <div className={styles.main_images_container}>
                    <Carousel onZoom={() => setZoom(true)} />
                </div>

                <div className={styles.main_info_container}>
                    <Info />
                </div>
            </main>

            {zoom ? <LightBox onLight={() => setZoom(false)} /> : null}
        </div>
    );
};
