import Head from "next/head";
import styles from "../styles/Home.module.scss";

import Menu from "../svgs/icon-menu.svg";
import Close from "../svgs/icon-close.svg";
import Logo from "../svgs/logo.svg";
import Cart from "../svgs/icon-cart.svg";
import Delete from "../svgs/icon-delete.svg";
import Carousel from "../components/carousel";
import Info from "../components/info";
import LightBox from "../components/lightBox";

import { useState } from "react";

export default function Home() {
    const [open, setOpen] = useState<boolean>(false);
    const [numberOfItems, setNumberOfItems] = useState<number>(0);
    const [showNumberOfItems, setShowNumberOfItems] = useState<boolean>(false);
    const [showCart, setShowCart] = useState<boolean>(false);
    const [zoom, setZoom] = useState<boolean>(false);

    /**/
    function removeItems() {
        if (numberOfItems <= 0) {
            return setNumberOfItems(0);
        }
        return setNumberOfItems(prevNumber => prevNumber - 1);
    }

    function addItems() {
        return setNumberOfItems(prevNumber => prevNumber + 1);
    }

    function getFinalPrice(items: number) {
        const itemPrice = 125;
        return (itemPrice * items).toFixed(2);
    }

    return (
        <div
            className={`${styles.main_container} ${
                open ? styles.main_container_background_mobile : null
            } ${zoom ? styles.main_container_background_zoom : null} `}
        >
            <Head>
                <title>Frontend Mentor | E-commerce product page</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/images/favicon-32x32.png" />
            </Head>
            <header className={styles.header}>
                <button
                    type="button"
                    title="menu"
                    className={styles.menu_btn}
                    onClick={() => setOpen(!open)}
                >
                    {!open ? <Menu /> : <Close />}
                </button>
                <Logo />
                <nav
                    className={`${styles.navigation} ${
                        open ? styles.navigation_mobile : null
                    }`}
                >
                    <a href="#">Collections</a>
                    <a href="#"> Men</a>
                    <a href="#">Women</a>
                    <a href="#"> About</a>
                    <a href="#"> Contact</a>
                </nav>
                <div className={styles.cart_container}>
                    <div className={styles.cart_wrap}>
                        <button
                            type="button"
                            title="basket"
                            onClick={() => setShowCart(!showCart)}
                            className={styles.cart_btn}
                        >
                            <Cart />
                        </button>
                        {numberOfItems !== 0 && showNumberOfItems ? (
                            <p>{numberOfItems}</p>
                        ) : null}
                    </div>
                    <button
                        type="button"
                        title="avatar"
                        onClick={() => setShowCart(!showCart)}
                        className={styles.cart_btn}
                    >
                        <img src="/images/image-avatar.png" alt="avatar" />
                    </button>
                </div>
                {showCart ? (
                    <div className={styles.basket_container}>
                        <h5>Cart</h5>

                        <div className={styles.basket_details}>
                            {numberOfItems === 0 ? (
                                <p>Your cart is empty</p>
                            ) : (
                                <>
                                    <div className={styles.basket}>
                                        <img
                                            src="/images/image-product-1-thumbnail.jpg"
                                            alt=""
                                        />
                                        <div className={styles.details}>
                                            <p>Fall Limited Edition Sneakers</p>
                                            <p>
                                                $125.00 x {numberOfItems}
                                                <span>
                                                    $
                                                    {getFinalPrice(
                                                        numberOfItems
                                                    )}
                                                </span>
                                            </p>
                                        </div>
                                        <button
                                            type="button"
                                            title="delete"
                                            onClick={() => {
                                                setNumberOfItems(0),
                                                    setShowNumberOfItems(false),
                                                    setShowCart(false);
                                            }}
                                            className={styles.cart_btn}
                                        >
                                            <Delete />
                                        </button>
                                    </div>

                                    <button
                                        type="button"
                                        title="checkout"
                                        className={styles.checkout_btn}
                                        onClick={() => setShowCart(false)}
                                    >
                                        Checkout
                                    </button>
                                </>
                            )}
                        </div>
                    </div>
                ) : null}
            </header>
            <main className={styles.main}>
                <div className={styles.main_images_container}>
                    <Carousel onZoom={() => setZoom(true)} />
                </div>

                <div className={styles.main_info_container}>
                    <Info
                        onRemove={removeItems}
                        onAdd={addItems}
                        numberOfItems={numberOfItems}
                        onShowNumberOfItems={() => setShowNumberOfItems(true)}
                    />
                </div>
            </main>
            {zoom ? <LightBox onLight={() => setZoom(false)} /> : null}
        </div>
    );
}
